name: Tests
on: push

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - name: Clone Project
        uses: actions/checkout@v2

      - name: Run Lucid CodeGen tests
        run: |
          swift test --package-path CodeGen --enable-test-discovery
