name: Tests
on: push

jobs:
  codegen_tests:
    runs-on: ubuntu-latest
    steps:
      - name: Clone Project
        uses: actions/checkout@v2

      - name: Run Lucid CodeGen tests
        run: |
          swift test --package-path CodeGen --enable-test-discovery --enable-code-coverage
          echo "::set-env name=PRODUCT_PATH::`swift build --package-path CodeGen --show-bin-path`"

      - name: Create code coverage
        if: github.ref == 'refs/heads/master'
        uses: mattpolzin/swift-codecov-action@0.4.0
        with:
          CODECOV_JSON: ${{ env.PRODUCT_PATH }}/codecov/*.json

      - name: Upload code coverage badge
        if: github.ref == 'refs/heads/master'
        uses: alvivi/shield-badge@v1
        with:
          aws-access-key-id: ${{ secrets.S3_ACCESS_KEY }}
          aws-secret-access-key: ${{ secrets.S3_SECRET_ACCESS_KEY }}
          aws-region: us-east-1
          aws-bucket: mobile.scribd.com
          aws-filepath: badges/Lucid/CodeGen
          label: CodeGen Coverage
          text: ${{ env.CODECOV }}

  lucid_tests:
    name: Lucid-iOS Tests
    runs-on: macos-latest
    env: 
      FASTLANE_LOGS: fastlane/test_output
      DEVELOPER_DIR: /Applications/Xcode_11.2.1.app/Contents/Developer
      GITHUB_ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
    steps:
      - name: Clone Project
        uses: actions/checkout@v2

      - name: Bootstrap
        run: |
          carthage bootstrap --platform iOS

      - name: Run Lucid-iOS Tests
        run: |
          fastlane scan --scheme Lucid-iOS --device "iPhone 8" --output_directory $FASTLANE_LOGS --result_bundle true

      - name: Bundle Log Files
        if: ${{ always() }}
        run: |
          cd $FASTLANE_LOGS
          zip -rX build-artifacts.zip .

      - name: Upload Log Files
        if: ${{ always() }}
        uses: actions/upload-artifact@v2
        with:
          name: build-artifacts
          path: ${{ env.FASTLANE_LOGS }}/build-artifacts.zip
