name: Tests
on: push

jobs:
  codegen_tests:
    runs-on: ubuntu-latest
    steps:
      - name: Clone Project
        uses: actions/checkout@v2

      - name: Run Lucid CodeGen tests
        run: |
          swift test --package-path CodeGen --enable-test-discovery --enable-code-coverage
          echo "::set-env name=PRODUCT_PATH::`swift build --package-path CodeGen --show-bin-path`"

      - name: Create code coverage
        if: github.ref == 'refs/heads/master'
        uses: mattpolzin/swift-codecov-action@0.4.0
        with:
          CODECOV_JSON: ${{ env.PRODUCT_PATH }}/codecov/*.json

      - name: Upload code coverage badge
        if: github.ref == 'refs/heads/master'
        uses: alvivi/shield-badge@v1
        with:
          aws-access-key-id: ${{ secrets.S3_ACCESS_KEY }}
          aws-secret-access-key: ${{ secrets.S3_SECRET_ACCESS_KEY }}
          aws-region: us-east-1
          aws-bucket: mobile.scribd.com
          aws-filepath: badges/Lucid/CodeGen
          label: CodeGen Coverage
          text: ${{ env.CODECOV }}

  carthage_test:
    runs-on: macos-latest
    env: 
      DEVELOPER_DIR: /Applications/Xcode_11.2.1.app/Contents/Developer
      GITHUB_ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
      CARTHAGE_DEBUG_OUTPUT: /tmp/carthage_debug_output.txt
      CARTHAGE_RELEASE_OUTPUT: /tmp/carthage_release_output.txt

    steps:
      - name: Build Lucid Framework Using Carthage
        run: |
          echo 'git "git@github.com:scribd/Lucid.git" "master"' > Cartfile
          
          carthage bootstrap --platform iOS,watchOS --configuration Debug --log-path $CARTHAGE_DEBUG_OUTPUT
          carthage bootstrap --platform iOS,watchOS --configuration Release --log-path $CARTHAGE_RELEASE_OUTPUT

      - name: Upload Log Files
        if: ${{ always() }}
        uses: actions/upload-artifact@v2
        with:
          name: build-log
          path: |
            ${{ env.CARTHAGE_DEBUG_OUTPUT }}
            ${{ env.CARTHAGE_RELEASE_OUTPUT }}
